export const sem_dias = [
  ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
  ["lun", "mar", "mié", "jue", "vie", "sáb", "dom"],
  ["lu", "ma", "mi", "ju", "vi", "sá", "do"],
]

export const lista_dias = [
  {
    nombre: "Enero",
    dias: "31",
    dias_f: [1, 31],
    año: 2024,
    r_dias: ["lu", "mi"],
    r_dias2: ["lun", "mié"],
    r_dias_c: ["Lunes", "Miércoles"],
    vacio: 0,
  },
  {
    nombre: "Febrero",
    dias: "29",
    dias_f: [32, 60],
    año: 2024,
    r_dias: ["ju", "ju"],
    r_dias2: ["jue", "jue"],
    r_dias_c: ["Jueves", "Jueves"],
    vacio: 3,
  },
  {
    nombre: "Marzo",
    dias: "31",
    dias_f: [61, 91],
    año: 2024,
    r_dias: ["vi", "do"],
    r_dias2: ["vie", "dom"],
    r_dias_c: ["Viernes", "Domingo"],
    vacio: 4,
  },
  {
    nombre: "Abril",
    dias: "30",
    dias_f: [92, 121],
    año: 2024,
    r_dias: ["lu", "ma"],
    r_dias2: ["lun", "mar"],
    r_dias_c: ["Lunes", "Martes"],
    vacio: 0,
  },
  {
    nombre: "Mayo",
    dias: "31",
    dias_f: [122, 152],
    año: 2024,
    r_dias: ["mi", "vi"],
    r_dias2: ["mié", "vie"],
    r_dias_c: ["Miércoles", "Viernes"],
    vacio: 2,
  },
  {
    nombre: "Junio",
    dias: "30",
    dias_f: [153, 182],
    año: 2024,
    r_dias: ["sá", "do"],
    r_dias2: ["sáb", "dom"],
    r_dias_c: ["Sábado", "Domingo"],
    vacio: 5,
  },
  {
    nombre: "Julio",
    dias: "31",
    dias_f: [183, 213],
    año: 2024,
    r_dias: ["lu", "mi"],
    r_dias2: ["lun", "mié"],
    r_dias_c: ["Lunes", "Miércoles"],
    vacio: 0,
  },
  {
    nombre: "Agosto",
    dias: "31",
    dias_f: [214, 244],
    año: 2024,
    r_dias: ["ju", "sá"],
    r_dias2: ["jue", "sáb"],
    r_dias_c: ["Jueves", "Sábado"],
    vacio: 3,
  },
  {
    nombre: "Septiembre",
    dias: "30",
    dias_f: [245, 274],
    año: 2024,
    r_dias: ["do", "lu"],
    r_dias2: ["dom", "lun"],
    r_dias_c: ["Domingo", "Lunes"],
    vacio: 6,
  },
  {
    nombre: "Octubre",
    dias: "31",
    dias_f: [275, 305],
    año: 2024,
    r_dias: ["ma", "ju"],
    r_dias2: ["mar", "jue"],
    r_dias_c: ["Martes", "Jueves"],
    vacio: 1,
  },
  {
    nombre: "Noviembre",
    dias: "30",
    dias_f: [306, 355],
    año: 2024,
    r_dias: ["vi", "sá"],
    r_dias2: ["vie", "sáb"],
    r_dias_c: ["Viernes", "Sábado"],
    vacio: 4,
  },
  {
    nombre: "Diciembre",
    dias: "31",
    dias_f: [336, 366],
    año: 2024,
    r_dias: ["do", "ma"],
    r_dias2: ["dom", "mar"],
    r_dias_c: ["Domingo", "Martes"],
    vacio: 6,
  }
]

export const lista_meses = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
]

export const options = {
  a: "Nombres largos",
  b: "Nombres cortos (3)",
  c: "Nombres cortos (2)",
}